import type { OpenAPIHono } from '@hono/zod-openapi';
import { achievementsRoutes } from './achievements.js';
import { adminFlipSourcesRoutes } from './admin-flip-sources.js';
import { adminPacksRoutes } from './admin-packs.js';
import { adminRulesRoutes } from './admin-rules.js';
import { adminSupportRoutes } from './admin-support.js';
import { adminRoutes } from './admin.js';
import { arRoutes } from './ar.js';
import { billingRoutes } from './billing.js';
import { dailyChallengeRoutes } from './daily-challenge.js';
import { feedRoutes } from './feed.js';
import { flipSourcesRoutes } from './flip-sources.js';
import { genresRoutes } from './genres.js';
import { healthRoutes } from './health.js';
import { internalAlertsRoutes } from './internal-alerts.js';
import { leaderboardRoutes } from './leaderboard.js';
import { lobbiesRoutes } from './lobbies.js';
import { matchChatRoutes } from './match-chat.js';
import { matchesRoutes } from './matches.js';
import { meRoutes } from './me.js';
import { phasesRoutes } from './phases.js';
import { playlistsRoutes } from './playlists.js';
import { reportsRoutes } from './reports.js';
import { roomActionsRoutes } from './room-actions.js';
import { samplePacksRoutes } from './sample-packs.js';
import { statsRoutes } from './stats.js';
import { submissionsRoutes } from './submissions.js';
import { supportRoutes } from './support.js';
import { tournamentScheduleRoutes } from './tournament-schedule.js';
import { tournamentShowcaseRoutes } from './tournament-showcase.js';
import { tournamentsRoutes } from './tournaments.js';
import { userPacksRoutes } from './user-packs.js';

export function registerRoutes(app: OpenAPIHono): void {
  app.route('/', healthRoutes);
  app.route('/', internalAlertsRoutes);
  app.route('/', statsRoutes);
  app.route('/', feedRoutes);
  app.route('/', genresRoutes);
  app.route('/', matchesRoutes);
  app.route('/', lobbiesRoutes);
  app.route('/', roomActionsRoutes);
  app.route('/', matchChatRoutes);
  app.route('/', samplePacksRoutes);
  app.route('/', submissionsRoutes);
  app.route('/', phasesRoutes);
  app.route('/', arRoutes);
  app.route('/', adminRoutes);
  app.route('/', userPacksRoutes);
  app.route('/', leaderboardRoutes);
  app.route('/', dailyChallengeRoutes);
  app.route('/', adminFlipSourcesRoutes);
  app.route('/', adminPacksRoutes);
  app.route('/', adminRulesRoutes);
  app.route('/', flipSourcesRoutes);
  app.route('/', meRoutes);
  app.route('/', billingRoutes);
  app.route('/', playlistsRoutes);
  app.route('/', achievementsRoutes);
  app.route('/', reportsRoutes);
  app.route('/', supportRoutes);
  app.route('/', adminSupportRoutes);
  app.route('/', tournamentsRoutes);
  app.route('/', tournamentScheduleRoutes);
  app.route('/', tournamentShowcaseRoutes);
}
