// User-facing /reports endpoint and admin moderation queue.
//
//   POST  /reports                     authenticated, anyone can file
//   GET   /admin/reports               admin only, list (open by default)
//   PATCH /admin/reports/:id           admin only, resolve / dismiss / action

import { OpenAPIHono, createRoute, z } from '@hono/zod-openapi';
import { and, desc, eq, sql } from 'drizzle-orm';
import { db } from '../db/client.js';
import { reports } from '../db/schema.js';

export const reportsRoutes = new OpenAPIHono();

const ErrorBody = z.object({ error: z.string(), message: z.string() });

const SubjectType = z.enum(['submission', 'profile', 'pack', 'genre']);
const Reason = z.enum([
  'copyright',
  'nsfw',
  'harassment',
  'hate',
  'spam',
  'impersonation',
  'low_quality',
  'vote_ring', // system-generated by vote-ring auto-detector
  'dmca_counter_notice', // uploader rebuttal of a copyright report
  'other',
]);
const Status = z.enum(['open', 'actioned', 'dismissed']);

const ReportRow = z.object({
  id: z.string().uuid(),
  subjectType: SubjectType,
  subjectId: z.string().uuid(),
  reporterId: z.string().uuid().nullable(),
  reason: Reason,
  notes: z.string().nullable(),
  status: Status,
  createdAt: z.string().datetime(),
  reviewedAt: z.string().datetime().nullable(),
  reviewerNote: z.string().nullable(),
});

// ─── POST /reports ──────────────────────────────────────────────────────────

const submitBody = z.object({
  subjectType: SubjectType,
  subjectId: z.string().uuid(),
  reason: Reason,
  notes: z.string().max(1000).optional(),
});

const submitRoute = createRoute({
  method: 'post',
  path: '/reports',
  tags: ['reports'],
  summary: 'File a report against a submission, profile, pack, or genre',
  request: { body: { content: { 'application/json': { schema: submitBody } } } },
  responses: {
    201: {
      description: 'Filed',
      content: {
        'application/json': { schema: z.object({ id: z.string().uuid() }) },
      },
    },
    401: {
      description: 'Unauthenticated',
      content: { 'application/json': { schema: ErrorBody } },
    },
  },
});

reportsRoutes.openapi(submitRoute, async (c) => {
  const user = c.var.user;
  if (!user) return c.json({ error: 'unauthenticated', message: 'Sign in to report.' }, 401);

  const body = c.req.valid('json');
  const [row] = await db()
    .insert(reports)
    .values({
      subjectType: body.subjectType,
      subjectId: body.subjectId,
      reporterId: user.id,
      reason: body.reason,
      notes: body.notes ?? null,
    })
    .returning({ id: reports.id });
  if (!row) {
    return c.json({ error: 'unauthenticated', message: 'Insert failed.' }, 401);
  }
  return c.json({ id: row.id }, 201);
});

// ─── GET /admin/reports ─────────────────────────────────────────────────────

const listRoute = createRoute({
  method: 'get',
  path: '/admin/reports',
  tags: ['admin', 'reports'],
  summary: 'List reports for moderation',
  request: {
    query: z.object({
      status: Status.optional().default('open'),
    }),
  },
  responses: {
    200: {
      description: 'Reports',
      content: {
        'application/json': { schema: z.object({ items: z.array(ReportRow) }) },
      },
    },
    401: { description: 'Unauthenticated', content: { 'application/json': { schema: ErrorBody } } },
    403: { description: 'Not an admin', content: { 'application/json': { schema: ErrorBody } } },
  },
});

reportsRoutes.openapi(listRoute, async (c) => {
  const user = c.var.user;
  if (!user) return c.json({ error: 'unauthenticated', message: 'Sign in.' }, 401);
  if (user.role !== 'admin')
    return c.json({ error: 'forbidden', message: 'Admin role required.' }, 403);

  const { status } = c.req.valid('query');
  const rows = await db()
    .select()
    .from(reports)
    .where(eq(reports.status, status))
    .orderBy(desc(reports.createdAt))
    .limit(200);

  return c.json(
    {
      items: rows.map((r) => ({
        id: r.id,
        subjectType: r.subjectType as z.infer<typeof SubjectType>,
        subjectId: r.subjectId,
        reporterId: r.reporterId,
        reason: r.reason as z.infer<typeof Reason>,
        notes: r.notes,
        status: r.status as z.infer<typeof Status>,
        createdAt: r.createdAt.toISOString(),
        reviewedAt: r.reviewedAt ? r.reviewedAt.toISOString() : null,
        reviewerNote: r.reviewerNote,
      })),
    },
    200,
  );
});

// ─── GET /me/reports ────────────────────────────────────────────────────────
//
// Open reports targeting content the caller owns (their packs, their
// profile). Used to drive the "Open issues" section on /settings so the
// uploader can file a counter-notice on a copyright report.

const myReportsRoute = createRoute({
  method: 'get',
  path: '/me/reports',
  tags: ['reports'],
  summary: "Open reports filed against the caller's content",
  responses: {
    200: {
      description: 'Reports against the caller',
      content: {
        'application/json': {
          schema: z.object({
            items: z.array(
              ReportRow.extend({
                subjectLabel: z.string(),
              }),
            ),
          }),
        },
      },
    },
    401: {
      description: 'Unauthenticated',
      content: { 'application/json': { schema: ErrorBody } },
    },
  },
});

reportsRoutes.openapi(myReportsRoute, async (c) => {
  const user = c.var.user;
  if (!user) return c.json({ error: 'unauthenticated', message: 'Sign in.' }, 401);

  const d = db();
  // Reports against your profile + reports against any sample_pack you
  // created. Exclude system-generated vote_ring reports (those go to
  // admin, not the user).
  const rows = await d.execute<{
    id: string;
    subject_type: string;
    subject_id: string;
    reporter_id: string | null;
    reason: string;
    notes: string | null;
    status: string;
    created_at: Date | string;
    reviewed_at: Date | string | null;
    reviewer_note: string | null;
    subject_label: string;
  }>(
    sql`SELECT r.id, r.subject_type, r.subject_id, r.reporter_id, r.reason, r.notes,
               r.status, r.created_at, r.reviewed_at, r.reviewer_note,
               COALESCE(sp.name, 'profile') AS subject_label
          FROM reports r
          LEFT JOIN sample_packs sp ON sp.id = r.subject_id AND r.subject_type = 'pack'
         WHERE r.status = 'open'
           AND r.reason != 'vote_ring'
           AND (
             (r.subject_type = 'profile' AND r.subject_id = ${user.id})
             OR (r.subject_type = 'pack' AND sp.created_by = ${user.id})
           )
         ORDER BY r.created_at DESC
         LIMIT 50`,
  );
  const arr = rows as Array<{
    id: string;
    subject_type: string;
    subject_id: string;
    reporter_id: string | null;
    reason: string;
    notes: string | null;
    status: string;
    created_at: Date | string;
    reviewed_at: Date | string | null;
    reviewer_note: string | null;
    subject_label: string;
  }>;

  return c.json(
    {
      items: arr.map((r) => ({
        id: r.id,
        subjectType: r.subject_type as z.infer<typeof SubjectType>,
        subjectId: r.subject_id,
        reporterId: r.reporter_id,
        reason: r.reason as z.infer<typeof Reason>,
        notes: r.notes,
        status: r.status as z.infer<typeof Status>,
        createdAt: new Date(r.created_at).toISOString(),
        reviewedAt: r.reviewed_at ? new Date(r.reviewed_at).toISOString() : null,
        reviewerNote: r.reviewer_note,
        subjectLabel: r.subject_label,
      })),
    },
    200,
  );
});

// ─── POST /reports/:id/counter-notice ───────────────────────────────────────
//
// File a counter-notice referencing an open report. Creates a paired
// report row with reason='dmca_counter_notice' and notes that include
// the original report id. Admins see the pair in the queue and can
// resolve both.

const counterBody = z.object({
  statement: z.string().min(20).max(2000),
});

const counterRoute = createRoute({
  method: 'post',
  path: '/reports/{id}/counter-notice',
  tags: ['reports'],
  summary: 'File a counter-notice on a copyright report',
  request: {
    params: z.object({ id: z.string().uuid() }),
    body: { content: { 'application/json': { schema: counterBody } } },
  },
  responses: {
    201: {
      description: 'Counter-notice filed',
      content: { 'application/json': { schema: z.object({ id: z.string().uuid() }) } },
    },
    400: {
      description: 'Original report not eligible',
      content: { 'application/json': { schema: ErrorBody } },
    },
    401: { description: 'Unauthenticated', content: { 'application/json': { schema: ErrorBody } } },
    403: {
      description: 'Not the content owner',
      content: { 'application/json': { schema: ErrorBody } },
    },
    404: {
      description: 'Report not found',
      content: { 'application/json': { schema: ErrorBody } },
    },
  },
});

reportsRoutes.openapi(counterRoute, async (c) => {
  const user = c.var.user;
  if (!user) return c.json({ error: 'unauthenticated', message: 'Sign in.' }, 401);

  const { id } = c.req.valid('param');
  const { statement } = c.req.valid('json');
  const d = db();

  // Look up the original report and validate ownership of the subject.
  const [orig] = await d.select().from(reports).where(eq(reports.id, id)).limit(1);
  if (!orig) return c.json({ error: 'not_found', message: 'Report not found.' }, 404);
  if (orig.status !== 'open')
    return c.json({ error: 'closed', message: 'Original report is already resolved.' }, 400);
  if (orig.reason !== 'copyright')
    return c.json(
      { error: 'wrong_reason', message: 'Counter-notice only applies to copyright reports.' },
      400,
    );

  // Owner check varies by subject_type.
  let ownsSubject = false;
  if (orig.subjectType === 'profile') {
    ownsSubject = orig.subjectId === user.id;
  } else if (orig.subjectType === 'pack') {
    const own = await d.execute<{ created_by: string | null }>(
      sql`SELECT created_by FROM sample_packs WHERE id = ${orig.subjectId} LIMIT 1`,
    );
    const r0 = (own as Array<{ created_by: string | null }>)[0];
    ownsSubject = r0?.created_by === user.id;
  }
  if (!ownsSubject)
    return c.json(
      { error: 'forbidden', message: 'Only the content owner can file a counter-notice.' },
      403,
    );

  const [row] = await d
    .insert(reports)
    .values({
      subjectType: orig.subjectType,
      subjectId: orig.subjectId,
      reporterId: user.id,
      reason: 'dmca_counter_notice',
      notes: `counter-notice for report=${orig.id}\n\n${statement}`,
    })
    .returning({ id: reports.id });
  if (!row)
    return c.json({ error: 'insert_failed', message: 'Could not file counter-notice.' }, 400);
  return c.json({ id: row.id }, 201);
});

// ─── PATCH /admin/reports/:id ───────────────────────────────────────────────

const resolveBody = z.object({
  status: z.enum(['actioned', 'dismissed']),
  reviewerNote: z.string().max(1000).optional(),
});

const resolveRoute = createRoute({
  method: 'patch',
  path: '/admin/reports/{id}',
  tags: ['admin', 'reports'],
  summary: 'Resolve a report (action taken or dismissed)',
  request: {
    params: z.object({ id: z.string().uuid() }),
    body: { content: { 'application/json': { schema: resolveBody } } },
  },
  responses: {
    200: {
      description: 'Resolved',
      content: {
        'application/json': { schema: z.object({ id: z.string().uuid(), status: Status }) },
      },
    },
    401: { description: 'Unauthenticated', content: { 'application/json': { schema: ErrorBody } } },
    403: { description: 'Not an admin', content: { 'application/json': { schema: ErrorBody } } },
    404: { description: 'Not found', content: { 'application/json': { schema: ErrorBody } } },
  },
});

reportsRoutes.openapi(resolveRoute, async (c) => {
  const user = c.var.user;
  if (!user) return c.json({ error: 'unauthenticated', message: 'Sign in.' }, 401);
  if (user.role !== 'admin')
    return c.json({ error: 'forbidden', message: 'Admin role required.' }, 403);

  const { id } = c.req.valid('param');
  const body = c.req.valid('json');

  const result = await db()
    .update(reports)
    .set({
      status: body.status,
      reviewedBy: user.id,
      reviewedAt: new Date(),
      reviewerNote: body.reviewerNote ?? null,
    })
    .where(and(eq(reports.id, id), eq(reports.status, 'open')))
    .returning({ id: reports.id, status: reports.status });

  const row = result[0];
  if (!row) return c.json({ error: 'not_found', message: 'Already resolved or missing.' }, 404);
  return c.json({ id: row.id, status: row.status as z.infer<typeof Status> }, 200);
});

// Stub to avoid unused-import lint. Drizzle's `sql` is used in seed; keep
// it imported here so future moderation queries (e.g., reporter-honor
// weighting) have it ready.
void sql;
